apiVersion: mailjail.io/v1alpha1
kind: MailStack

metadata:
  name: mx1

host:
  hostname: mx1.example.com
  externalInterface: vtnet0
  zfsPool: zroot
  jailDatasetRoot: zroot/mailjail

network:
  domain: example.com
  bridge: bridge0
  jailsSubnet: 10.77.0.0/24
  gateway4: 10.77.0.1

tls:
  mode: acme
  email: admin@example.com

modules:
  postfix:
    enabled: true
    ip4: 10.77.0.10
  dovecot:
    enabled: true
    ip4: 10.77.0.11
  rspamd:
    enabled: true
    ip4: 10.77.0.12
  redis:
    enabled: true
    ip4: 10.77.0.13
  db:
    enabled: true
    ip4: 10.77.0.14
  web:
    enabled: true
    ip4: 10.77.0.15
